### PR TITLE
[2.7.3] fix build with OpenSSL 1.1

### PR DESCRIPTION
**Pull request by remicollet**
```
/builddir/build/BUILD/libcouchbase-2.7.3/src/ssl/ssl_common.c: In function 'iotssl_log_errors':
/builddir/build/BUILD/libcouchbase-2.7.3/src/ssl/ssl_common.c:159:18: error: 'SSL_R_MISSING_VERIFY_MESSAGE' undeclared (first use in this function); did you mean 'SSL_R_MISSING_SRP_PARAM'?
             case SSL_R_MISSING_VERIFY_MESSAGE:
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  SSL_R_MISSING_SRP_PARAM
```

### CODE REVIEW

**Comment by avsej** [comment]
@mnunberg I moved it to gerrit http://review.couchbase.org/75599
